from __future__ import annotations

GOLDEN_COMMANDS_V1 = [
    {
        "id": "daily_briefing",
        "phrase": "briefing",
        "expected_action": "daily_briefing",
        "expected_params": {},
        "risk": "read",
        "requires_confirmation": False,
        "status": "ready",
    },
    {
        "id": "daily_routine",
        "phrase": "rotina diaria",
        "expected_action": "daily_routine",
        "expected_params": {},
        "risk": "read",
        "requires_confirmation": False,
        "status": "ready",
    },
    {
        "id": "start_day",
        "phrase": "comecar meu dia",
        "expected_action": "daily_routine",
        "expected_params": {},
        "risk": "read",
        "requires_confirmation": False,
        "status": "ready",
    },
    {
        "id": "weather_city",
        "phrase": "clima em Salvador",
        "expected_action": "weather_summary",
        "expected_params": {"location": "Salvador"},
        "risk": "read",
        "requires_confirmation": False,
        "status": "ready",
    },
    {
        "id": "agenda_today",
        "phrase": "agenda de hoje",
        "expected_action": "agenda_list_today",
        "expected_params": {},
        "risk": "read",
        "requires_confirmation": False,
        "status": "ready",
    },
    {
        "id": "reminders_list",
        "phrase": "lembretes",
        "expected_action": "reminder_list",
        "expected_params": {},
        "risk": "read",
        "requires_confirmation": False,
        "status": "ready",
    },
    {
        "id": "telegram_status",
        "phrase": "status do telegram",
        "expected_action": "telegram.status",
        "expected_params": {},
        "risk": "read",
        "requires_confirmation": False,
        "status": "ready",
    },
    {
        "id": "telegram_start",
        "phrase": "iniciar bot telegram",
        "expected_action": "telegram.start_bot",
        "expected_params": {},
        "risk": "local_action",
        "requires_confirmation": False,
        "status": "ready",
    },
    {
        "id": "memory_backup_create",
        "phrase": "criar backup da memoria",
        "expected_action": "action_tool_execute",
        "expected_params": {"name": "memory.backup.create", "arguments": {}},
        "risk": "write",
        "requires_confirmation": False,
        "status": "ready",
    },
    {
        "id": "memory_backup_list",
        "phrase": "listar backups da memoria",
        "expected_action": "action_tool_execute",
        "expected_params": {"name": "memory.backup.list", "arguments": {}},
        "risk": "read",
        "requires_confirmation": False,
        "status": "ready",
    },
    {
        "id": "open_spotify",
        "phrase": "abrir spotify",
        "expected_action": "open_app",
        "expected_params": {"target": "spotify"},
        "risk": "local_action",
        "requires_confirmation": False,
        "status": "ready",
    },
    {
        "id": "close_spotify",
        "phrase": "fecha spotify",
        "expected_action": "close_app",
        "expected_params": {"target": "spotify"},
        "risk": "high",
        "requires_confirmation": True,
        "status": "ready",
    },
    {
        "id": "media_pause",
        "phrase": "pausar musica",
        "expected_action": "media_play_pause",
        "expected_params": {},
        "risk": "local_action",
        "requires_confirmation": False,
        "status": "ready",
    },
    {
        "id": "volume_up",
        "phrase": "aumentar volume",
        "expected_action": "volume_up",
        "expected_params": {},
        "risk": "local_action",
        "requires_confirmation": False,
        "status": "ready",
    },
    {
        "id": "browser_new_tab",
        "phrase": "nova aba",
        "expected_action": "browser_new_tab",
        "expected_params": {},
        "risk": "local_action",
        "requires_confirmation": False,
        "status": "ready",
    },
    {
        "id": "browser_scroll_down",
        "phrase": "role para baixo",
        "expected_action": "browser_scroll_down",
        "expected_params": {},
        "risk": "local_action",
        "requires_confirmation": False,
        "status": "ready",
    },
    {
        "id": "vision_status",
        "phrase": "status da visao",
        "expected_action": "vision_status",
        "expected_params": {},
        "risk": "read",
        "requires_confirmation": False,
        "status": "ready",
    },
    {
        "id": "background_status",
        "phrase": "status das tarefas em segundo plano",
        "expected_action": "background_status",
        "expected_params": {},
        "risk": "read",
        "requires_confirmation": False,
        "status": "ready",
    },
    {
        "id": "bluetooth_status",
        "phrase": "status do bluetooth",
        "expected_action": "bluetooth_status",
        "expected_params": {},
        "risk": "read",
        "requires_confirmation": False,
        "status": "ready",
    },
    {
        "id": "list_files",
        "phrase": "listar arquivos",
        "expected_action": "list_files",
        "expected_params": {"path": ""},
        "risk": "read",
        "requires_confirmation": False,
        "status": "ready",
    },
]


def golden_command_count() -> int:
    return len(GOLDEN_COMMANDS_V1)


GOLDEN_UI_COMMANDS_V2 = [
    {
        "id": "hud_show",
        "phrase": "mostrar hud",
        "surface": "ui_bridge",
        "expected_response": "Interface ativada. Deixei o painel no ar.",
        "risk": "local_action",
        "status": "ready",
    },
    {
        "id": "hud_hide",
        "phrase": "fechar hud",
        "surface": "ui_bridge",
        "expected_response": "Interface oculta.",
        "risk": "local_action",
        "status": "ready",
    },
    {
        "id": "hud_status",
        "phrase": "status da interface",
        "surface": "ui_bridge",
        "expected_response": "Interface ativa.",
        "risk": "read",
        "status": "ready",
    },
    {
        "id": "health_panel",
        "phrase": "saude do axel",
        "surface": "ui_bridge",
        "expected_response_contains": "Saude do Axel:",
        "risk": "read",
        "status": "ready",
    },
    {
        "id": "skills_panel",
        "phrase": "abrir painel de skills",
        "surface": "ui_bridge",
        "expected_response": "Painel de skills aberto.",
        "risk": "read",
        "status": "ready",
    },
    {
        "id": "economy_mode",
        "phrase": "modo economia",
        "surface": "work_mode",
        "expected_response_contains": "Modo economia ativado",
        "risk": "local_action",
        "status": "ready",
    },
    {
        "id": "balanced_mode",
        "phrase": "modo equilibrado",
        "surface": "work_mode",
        "expected_response_contains": "Modo equilibrado ativado",
        "risk": "local_action",
        "status": "ready",
    },
    {
        "id": "performance_mode",
        "phrase": "modo performance",
        "surface": "work_mode",
        "expected_response_contains": "Modo performance ativado",
        "risk": "local_action",
        "status": "ready",
    },
]


def golden_ui_command_count() -> int:
    return len(GOLDEN_UI_COMMANDS_V2)
